### ISSUE TITLE
Error while trying to run pusher

### ISSUE THREAD

**Issue by triniwiz** [buddycloud/buddycloud-pusher#18]
java -jar target/pusher-0.1.0-jar-with-dependencies.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/xmpp/component/Log
    at org.buddycloud.pusher.Main.main(Main.java:41)
Caused by: java.lang.ClassNotFoundException: org.xmpp.component.Log
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more

**Comment by triniwiz** [comment]
So i got it to compile on another server and  transferred the .jar file and it runs but i still cannot get any emails or push notifications while using the buddycloud android app also theres no logs :/
